name: Build and Push Notification Microservice

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'services/ecomm-notification/**'
    branches: 
      - main

env:
  MS_NAME: ecomm-notification

jobs:
  build-and-push:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package -Ddockerfile.skip -DskipTests
      working-directory: services/${{ env.MS_NAME }}

    - name: Build & Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/${{ env.MS_NAME }}
        tags: latest
        registry: docker.io
        dockerfile: services/${{ env.MS_NAME }}/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: 'JAR_FILE=services/${{ env.MS_NAME }}/target/*.jar'
